import type { Metadata } from "next";
import { League_Spartan, Raleway } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// Initialize League Spartan font
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-league-spartan",
});

// Initialize Raleway font
const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${leagueSpartan.variable} ${raleway.variable}`}>
      <body className={`${leagueSpartan.className}`}>{children}</body>
    </html>
  );
}
